### ISSUE TITLE
isCopied is not reactive to other objects being copied.

### ISSUE THREAD

**Issue by aarohmankad** [danoc/react-use-clipboard#4]
I am rendering a list of colors

![image](https://user-images.githubusercontent.com/3311321/60363487-911a2800-9998-11e9-8f9e-137e90392c26.png)

When I click one of these colors, the local `isCopied` state is true.

![image](https://user-images.githubusercontent.com/3311321/60363515-a000da80-9998-11e9-93c9-104db3129199.png)

But when I click another color, the old color still maintains it's value of `isCopied`.

![image](https://user-images.githubusercontent.com/3311321/60363542-b27b1400-9998-11e9-8c4c-623d0704285b.png)

Is there any way to make sure that only one instance of `isCopied` is set to true?

**Comment by aarohmankad** [comment]
Here is an idea on how to maybe access this "global" clipboard state.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by danoc** [comment]
Hey @aarohmankad,

Two things come to mind:

1. For each color, you can conditionally show "Copied!" if `isCopied && latestCopiedColor === "#4277ae"`. `latestCopiedColor` can be a string with a color that you keep track of with state.
2. I'm thinking of adding an option to `react-use-clipboard` called `successDuration` that lets the user decide how long they want the `isCopied` boolean to remain true. You could use this to temporarily show a success message and then revert to showing the color hex.

What do you think?

**Comment by aarohmankad** [comment]
The `successDuration` solution seems nice! That's actually what I ended up implementing on my own. Let me know if you'd like a PR to that effect :)
