### ISSUE TITLE
Types not working

### ISSUE THREAD

**Issue by tu4mo** [danoc/react-use-clipboard#8]
Hi and thanks for the lib! I noticed that types are referring to `dist/react-use-clipboard.d.ts`, which doesn't exist in the package.

**Comment by danoc** [comment]
Hey @tu4mo — Thanks for the report. I just shipped a fix in v1.0.0. Let me know if that works!

**Comment by tu4mo** [comment]
@danoc Works great! Thank you!

**Comment by tu4mo** [comment]
@danoc Looks like this is bug is back in v1.0.5.

**Comment by danoc** [comment]
Ah, my bad. I will fix today.

**Comment by sct** [comment]
Was about to come report the same thing. Glad to see it's not just me 😆

**Comment by danoc** [comment]
This was released in 1.0.6. Thanks to all that contributed.

**Comment by tu4mo** [comment]
Thanks again! :+1:
